[package]
name = "frosty/vehicle-chassis"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
graphmodule = "boatbomber/graphmodule@1.0.0"
fusion = "elttob/fusion@0.2.0"
trove = "sleitnick/trove@1.0.0"
iris = "xswezan/iris@2.0.5"
